x-var:
  - &POSTGRES_USER
    postgres
  - &POSTGRES_PASSWORD
    default
  - &POSTGRES_DATABASE
    postgres

x-flyway-vars: &flyway-vars
  FLYWAY_URL: jdbc:postgresql://sampledb:5432/postgres
  FLYWAY_USER: *POSTGRES_USER
  FLYWAY_PASSWORD: *POSTGRES_PASSWORD
  FLYWAY_BASELINE_ON_MIGRATE: true

x-postgres-vars: &postgres-vars
  POSTGRES_HOST: sampledb
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

services:
  housing-unit-tests:
    profiles: ["test"]
    image: python:3.12
    container_name: housing-unit-tests
    entrypoint: /application/run-unit-tests.sh
    volumes: [".:/application", "/application/.venv"]
  
  database:
    image: postgres:15
    container_name: sampledb
    environment:
      <<: *postgres-vars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    ports: ["5432:5432"]

  housing-migration:
    image: flyway/flyway:10
    container_name: housing-migration
    command: info migrate info
    volumes: ["./db/migrations:/flyway/sql:ro"]
    environment:
      <<: *flyway-vars
      FLYWAY_DEFAULT_SCHEMA: housing
    depends_on:
      database:
        condition: service_healthy

  housing-api:
    container_name: housing-api
    image: ghcr.io/nalin28/sample-api:latest
    entrypoint: fastapi dev --host 0.0.0.0 --port 3000 src/sample_api/main.py
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # volumes: [".:/application", "/application/.venv"]
    environment:
      <<: [*postgres-vars]
    ports: ["3003:3000"]
    depends_on:
      housing-migration:
        condition: service_started

 
